### ISSUE TITLE
Length is displaying days, not hours

### ISSUE THREAD

**Issue by rodrigoargumedo** [Hackalist/ios#1]
Hi @espeneric,

Length should expect 24 hours instead of days.

![Issue](https://camo.githubusercontent.com/b93640073e3a748bc03d132b638b723a67e329e7/68747470733a2f2f646c322e7075736862756c6c657475736572636f6e74656e742e636f6d2f347a336162764b33765734614f4570715a4f52306943735368377754303165442f494d475f313432342e504e47)

**Comment by adriansergheev** [comment]
Thank you for pointing out. Will be fixed.
